In [5]:
import main as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


In [6]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [12]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [13]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [3]:
import main as np
# Universal Functions
np3=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
# square root
# print(np.sqrt(np2))
# absolute value 
# print(np.absolute(np2))
# exponents
# print(np.exp(np2))
# min/max
# print(np.min(np2))
# print(np.max(np2))

In [8]:
import main as np
# shaping and reshaping
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)
np2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(np2)
print(np2.shape)
np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [16]:
import main as np
# iterating
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
# for x in np1:
#     print(x)
np2 = np.array([[1,2,3,4,5], [7,8,9,10,11]])
# for x in np2:
#     for y in x:
#         print(y)
np3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
# for x in np3:
#     for y in x:
#         for z in y:
#             print(z)
for x in np.nditer(np3):
    print(x)



1
2
3
4
5
6
7
8
9
10
11
12


In [17]:
import main as np
# sorting
np1 = np.array([4,5,3,6,2,7,1,9])
print(np1)
print(np.sort(np1))

[4 5 3 6 2 7 1 9]
[1 2 3 4 5 6 7 9]


In [22]:
import main as np
# searching
np1 = np.array([1,2,3,4,5,6,7,3,8,9,10])
x = np.where(np1 ==3)
y = np.where(np1 % 2 == 0)
print(np1)
print(x[0])
print(np1[y[0]])


[ 1  2  3  4  5  6  7  3  8  9 10]
[2 7]
[ 2  4  6  8 10]


In [25]:
import main as np
# filtering
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = [True, True, False, False, False, False, False, False, False, False]
print(np1)
print(np1[x])
# filtered = []
# for thing in np1:
#     if thing % 2 == 0:
#         filtered.append(True)
#     else:
#         filtered.append(False)
# print(filtered)
# new = np1[filtered]
# print(new)
filtered = np1 % 2 == 0
print(filtered)
print(np1[filtered])


[ 1  2  3  4  5  6  7  8  9 10]
[1 2]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
